 # A-Star Algorithm
 * A-Star Algorithm to find the optimal path for the Maze 

In [1]:
import numpy as np

### Node class
* A node class for A* Pathfinding.
* The f, g, and h variables are in our Node class are initialised.


In [2]:
class Node():

    def __init__(self, parent=None, position=None):
        self.parent = parent
        self.position = position

        self.g = 0    #G is the distance between the current node and the start node.
        self.h = 0    #H is the heuristic — estimated distance from the current node to the end node.
        self.f = 0    #F is the total cost of the node

    def __eq__(self, other):
        return self.position == other.position 

###  A-Star Function
* Returns a list of tuples as a path from the given start to the given end in the given maze.



In [3]:
def astar(maze, start, end):

    # Create start and end node
    start_node = Node(None, start)
    start_node.g = start_node.h = start_node.f = 0
    end_node = Node(None, end)
    end_node.g = end_node.h = end_node.f = 0

    # Initialize both open and closed list
    open_list = []
    closed_list = []

    # Add the start node
    open_list.append(start_node)

    # Loop until you find the end
    while len(open_list) > 0:
        # Get the current node
        current_node = open_list[0]
        current_index = 0
        for index, item in enumerate(open_list):
            if item.f < current_node.f:
                current_node = item
                current_index = index

        # Pop current off open list, add to closed list
        temp = []
        for i in range(len(open_list)):
            if i == current_index:
                continue
            else:
                temp.append(open_list[i])
        open_list = temp
        closed_list.append(current_node)

        # Found the goal
        if current_node == end_node:
            path = []
            current = current_node
            while current is not None:
                path.append(current.position)
                current = current.parent
            return path[::-1] # Return reversed path                                                        
        
            

        # Generate children
        children = []
        for new_position in [(0, -1), (0, 1), (-1, 0), (1, 0), (-1, -1), (-1, 1), (1, -1), (1, 1)]: # Adjacent squares
            # Get node position
            node_position = (current_node.position[0] + new_position[0], current_node.position[1] + new_position[1])
        
            # Make sure within range
            if node_position[0] > (len(maze) - 1) or node_position[0] < 0 or node_position[1] > (len(maze[len(maze)-1]) -1) or node_position[1] < 0:
                  continue
            if node_position[0] < 0 or node_position[1] < 0:
                continue 
            # Make sure walkable terrain
            if maze[node_position[0]][node_position[1]] != 0:
                continue
            Current = current_node
            isPass = True
            # Check if the current node has been visited
            while Current is not None:
                
                if node_position[0] == Current.position[0] and node_position[1] == Current.position[1]:
                    isPass = False
                    break
                Current = Current.parent        
            if not isPass:
                continue 
            # Create new node
            new_node = Node(current_node, node_position)

            # Append
            children.append(new_node)

        # Loop through children
        for child in children:

            # Child is on the closed list
            for closed_child in closed_list:
                if child == closed_child:
                    continue

            # Create the f, g, and h values
            child.g = current_node.g + 1
            child.h = ((child.position[0] - end_node.position[0]) ** 2) + ((child.position[1] - end_node.position[1]) ** 2)
            child.f = child.g + child.h

            # Child is already in the open list
            for open_node in open_list:
                if child == open_node and child.g > open_node.g:
                    continue

            # Add the child to the open list
            open_list.append(child)
       



### Changing the Path tuples to a sequence of cell indexes

For example given: [(0, 0), (1, 1), (2, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7)]

return

0 9 18 27 28 29 30 31 

In [4]:
def getPathAsNumbers(path, width):
    newPath = ""
    for co in path:
        num = (co[0] *width) + co[1]
        newPath += str(num)+" "
    return newPath

### Read file : for each case, find the shortest path using A*
* Read the number of cases
* generate the matrix and initialise every cell to 0
* Read the obsticles and initialise them to 1


In [5]:
file1 = open("maze.txt","r+")
nextline = file1
caseNumber=file1.readline()
global obs_start  #Global variables
global obs_end #Global variables
global row    
    
for z in range(int(caseNumber)):
    caseLines = file1.readline()
    
    for w in range(int(caseLines)):
        line = file1.readline()
        x = line.split()
        if (len(x) == 6):
            height = int(x[0])
            width = int(x[1])
            start = (int(x[2]),int(x[3]))
            end = (int(x[4]),int(x[5]))
            arr = np.ndarray(shape=(height,width), dtype=int) # create matrix and initialise every cell to 0
            for r in range(height):  
                for c in range(width):
                    arr[r][c] = 0
        if (len(x) == 3):
            row = int(x[0])
            obs_start = int(x[1])
            obs_end = int(x[2])
            for i in range(obs_start, obs_end+1): # generating a list of numbers [4,5,6,7] for example 
                arr[row][i] = 1
    
    print(arr)
    path = astar(arr, start, end)
    
    if path is None:
        print("Case "+ str(z+1) + ": No path exist")
    else:
        print("Path :",path)
        print("Case "+ str(z+1) +": " ,getPathAsNumbers(path, width))
        print()

[[0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 1 1]
 [1 1 0 1 1 0 0 0]
 [1 0 0 0 0 0 0 0]]
Path : [(0, 0), (1, 1), (2, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7)]
Case 1:  0 9 18 27 28 29 30 31 

[[0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 1 1]
 [1 1 0 1 1 0 0 0]
 [1 0 0 0 0 0 0 0]]
Path : [(0, 0), (1, 1), (2, 2), (3, 1)]
Case 2:  0 9 18 25 

